# SPDX-FileCopyrightText: 2023 Jason Pena <jasonpena@awkless.com>
# SPDX-License-Identifier: MIT

# Page settings...
title: CHIP-8 Project
description: Documentation about the CHIP-8 emulation project

# Theme settings...
remote_theme: pages-themes/hacker@v0.2.0
plugins:
  - jekyll-remote-theme
